/*
  # Create Transition Scores and Mix Plans Tables

  ## Summary
  Stores pre-computed track compatibility scores and executable mix plans
  generated by the TransitionMatcher algorithm. These tables act as a cache
  layer so the frontend can instantly display suggestions and execute mixes
  without recomputing every time.

  ## New Tables

  1. `transition_scores`
     - One row per (track_a, track_b) pair
     - Composite unique index on (track_a_id, track_b_id) prevents duplicates
       and enables fast O(1) lookups
     - `stem_scores` JSONB stores per-stem-pair breakdown for debugging
     - `best_transition_type` is the algorithm's top recommendation
     - Nullable `transition_id` relates to the existing `transitions` table
       when a user has saved a transition between these tracks

  2. `mix_plans`
     - One row per planned or executed mix between two tracks
     - `stem_instructions` JSONB contains per-stem action sequences
       (fade_in, fade_out, cut, low_pass_sweep, etc.)
     - `fx_suggestions` JSONB contains reverb/delay parameters
     - `ai_generation_hooks` JSONB is a stub block; `enabled` is always false
       until a future AI generation phase activates it
     - `alternative_transitions` JSONB stores up to 4 ranked alternatives
     - Nullable `blend_id` relates to the existing `blends` table when a
       user publishes this mix as a blend

  ## Security
  - RLS enabled on both tables
  - Users can only access scores/plans for tracks they own
  - SELECT policy checks that the requesting user owns BOTH tracks in the pair

  ## Important Notes
  1. transition_scores should be recomputed when stem_analysis updates
  2. mix_plans.status starts as 'draft', moves to 'ready' after execute-mix validates it
  3. The composite index on transition_scores allows efficient "suggest next track" queries
*/

-- ============================================================
-- TABLE: transition_scores
-- ============================================================

CREATE TABLE IF NOT EXISTS transition_scores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  track_a_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  track_b_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Pre-computed match quality
  overall_score numeric(4, 3) CHECK (overall_score >= 0 AND overall_score <= 1),
  stem_scores jsonb DEFAULT '{}',
  best_transition_type text NOT NULL DEFAULT 'filter_fade',
  confidence numeric(4, 3) CHECK (confidence >= 0 AND confidence <= 1),

  -- Optional link to the existing transitions table
  transition_id uuid REFERENCES transitions(id) ON DELETE SET NULL,

  computed_at timestamptz DEFAULT now()
);

-- Composite unique index: only one score per ordered (A, B) pair per user
CREATE UNIQUE INDEX IF NOT EXISTS transition_scores_pair_user_idx
  ON transition_scores(track_a_id, track_b_id, user_id);

-- Index for "find all scores for track X" queries
CREATE INDEX IF NOT EXISTS transition_scores_track_a_idx ON transition_scores(track_a_id);
CREATE INDEX IF NOT EXISTS transition_scores_track_b_idx ON transition_scores(track_b_id);
CREATE INDEX IF NOT EXISTS transition_scores_user_idx ON transition_scores(user_id);
CREATE INDEX IF NOT EXISTS transition_scores_overall_idx ON transition_scores(overall_score DESC);

ALTER TABLE transition_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own transition scores"
  ON transition_scores FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own transition scores"
  ON transition_scores FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own transition scores"
  ON transition_scores FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own transition scores"
  ON transition_scores FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- ============================================================
-- TABLE: mix_plans
-- ============================================================

CREATE TABLE IF NOT EXISTS mix_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  track_a_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  track_b_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Algorithm output
  transition_type text NOT NULL DEFAULT 'filter_fade',
  confidence numeric(4, 3) CHECK (confidence >= 0 AND confidence <= 1),
  mix_point_ms integer NOT NULL DEFAULT 0,
  duration_ms integer NOT NULL DEFAULT 16000,

  -- Per-stem execution instructions
  stem_instructions jsonb DEFAULT '{}',
  fx_suggestions jsonb DEFAULT '{}',

  -- AI generation stub block (enabled: false by default)
  ai_generation_hooks jsonb DEFAULT '{"enabled": false, "requests": []}',

  -- Ranked alternatives
  alternative_transitions jsonb DEFAULT '[]',

  -- Execution lifecycle
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'ready', 'executing', 'complete')),

  -- Optional link to existing blends table
  blend_id uuid REFERENCES blends(id) ON DELETE SET NULL,

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mix_plans_track_a_idx ON mix_plans(track_a_id);
CREATE INDEX IF NOT EXISTS mix_plans_track_b_idx ON mix_plans(track_b_id);
CREATE INDEX IF NOT EXISTS mix_plans_user_idx ON mix_plans(user_id);
CREATE INDEX IF NOT EXISTS mix_plans_status_idx ON mix_plans(status);

ALTER TABLE mix_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own mix plans"
  ON mix_plans FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own mix plans"
  ON mix_plans FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own mix plans"
  ON mix_plans FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own mix plans"
  ON mix_plans FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);
